/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.checkerframework.specimin;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {
  @Test
  public void someLibraryMethodReturnsTrue() {
    // Library classUnderTest = new Library();
    // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
